2023-10-23 17:43:20.361 UTC [1] LOG:  starting PostgreSQL 16.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-10-23 17:43:20.362 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-10-23 17:43:20.362 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-10-23 17:43:20.394 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-23 17:43:20.623 UTC [25] LOG:  database system was shut down at 2023-10-23 17:22:40 UTC
2023-10-23 17:43:20.905 UTC [1] LOG:  database system is ready to accept connections
2023-10-23 17:48:20.612 UTC [23] LOG:  checkpoint starting: time
2023-10-23 17:48:20.892 UTC [23] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.091 s, sync=0.029 s, total=0.280 s; sync files=2, longest=0.016 s, average=0.015 s; distance=0 kB, estimate=0 kB; lsn=0/6584A58, redo lsn=0/6584A20
2023-10-23 17:53:20.979 UTC [23] LOG:  checkpoint starting: time
2023-10-23 17:53:21.902 UTC [23] LOG:  checkpoint complete: wrote 6 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.707 s, sync=0.011 s, total=0.923 s; sync files=3, longest=0.004 s, average=0.004 s; distance=7 kB, estimate=7 kB; lsn=0/65867F8, redo lsn=0/65867C0
2023-10-23 18:11:18.717 UTC [130] ERROR:  canceling statement due to user request
2023-10-23 18:11:18.717 UTC [130] STATEMENT:  create database dellstore2
	;
2023-10-23 18:13:21.156 UTC [23] LOG:  checkpoint starting: time
2023-10-23 18:14:58.136 UTC [23] LOG:  checkpoint complete: wrote 933 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=95.778 s, sync=1.018 s, total=96.980 s; sync files=311, longest=0.014 s, average=0.004 s; distance=8466 kB, estimate=8466 kB; lsn=0/724FB40, redo lsn=0/6DCB1B0
2023-10-23 18:56:34.872 UTC [319] FATAL:  password authentication failed for user "postgres"
2023-10-23 18:56:34.872 UTC [319] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 129: "host all all all scram-sha-256"
2023-10-23 18:58:08.947 UTC [326] FATAL:  password authentication failed for user "postgres"
2023-10-23 18:58:08.947 UTC [326] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 129: "host all all all scram-sha-256"
2023-10-23 19:08:17.050 UTC [377] FATAL:  password authentication failed for user "postgres"
2023-10-23 19:08:17.050 UTC [377] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 129: "host all all all scram-sha-256"
2023-10-23 19:08:36.981 UTC [380] FATAL:  password authentication failed for user "postgres"
2023-10-23 19:08:36.981 UTC [380] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 129: "host all all all scram-sha-256"
2023-10-23 19:09:55.162 UTC [389] ERROR:  extension "plpyrhon3u" is not available
2023-10-23 19:09:55.162 UTC [389] DETAIL:  Could not open extension control file "/usr/local/share/postgresql/extension/plpyrhon3u.control": No such file or directory.
2023-10-23 19:09:55.162 UTC [389] HINT:  The extension must first be installed on the system where PostgreSQL is running.
2023-10-23 19:09:55.162 UTC [389] STATEMENT:  --Primero debemos crear la extension plpython3u
	
	create extension plpyrhon3u
2023-10-23 19:10:04.656 UTC [389] ERROR:  extension "plpython3u" already exists
2023-10-23 19:10:04.656 UTC [389] STATEMENT:  --Primero debemos crear la extension plpython3u
	
	create extension plpython3u
2023-10-23 19:10:39.999 UTC [389] ERROR:  syntax error at or near "return" at character 1
2023-10-23 19:10:39.999 UTC [389] STATEMENT:  return plpy.execute(query)
	$$
	language plpython3u;
	
	
	
	/*
	 * 4. Sin usar funciones de ventana, implementar una funci칩n que muestre, por cada mes del a침o
	 * ingresado por par치metros, la cantidad de ordenes generadas, junto a la cantidad de ordenes
	 * acumuladas hasta ese mes (inclusive), recordar que para Python cada fila es un diccionario
	 * puede utilizar acumuladores, for y yeld*/
	create or replace function mostrar_ordenes_a침o(pd_year integer)
	returns table(li_month integer, li_qty_month integer, li_qty_acum integer) as
	$$
	query = """select date_part('month', orderdate) as li_month, count(*) as li_qty_month from orders where date_part('year', orderdate)="""
	query += str(pd_year)
	query += """ group by date_part('month', orderdate) order by date_part('month', orderdate);"""
2023-10-23 19:13:21.638 UTC [23] LOG:  checkpoint starting: time
2023-10-23 19:14:15.637 UTC [23] LOG:  checkpoint complete: wrote 526 buffers (3.2%); 0 WAL file(s) added, 0 removed, 1 recycled; write=53.777 s, sync=0.054 s, total=54.007 s; sync files=24, longest=0.008 s, average=0.003 s; distance=4723 kB, estimate=8092 kB; lsn=0/7268130, redo lsn=0/72680F8
